### ISSUE TITLE
My lineage14.1 for mi note pro boots!

### ISSUE THREAD

**Issue by GuaiYiHu** [GeyerA/device_xiaomi_leo#1]
Thanks to you a lot~~~~But still have some bugs...

**Comment by GeyerA** [comment]
Hi,
Interesting. My builds just did not boot. Is your code in Github? Which
vendor files did you use. Let me know if I still can help..
Laoshi

**Comment by GuaiYiHu** [comment]
I use ivan's aosp7.1.1 as vendor. Just can boot, it still has lots of bugs..... Where can I learn about how to fix this...

**Comment by GeyerA** [comment]
I also used these. Bug fixing is individual. The best might be to study the code in Mokee and apply to Leo...

**Comment by GuaiYiHu** [comment]
I have uploaded it on onedrive~ 
GPS, Wi-Fi, Bluetooth, phone call, camera, sensors work.
what doesn't work is hotpod. Ivan's aosp cannot use this guy too.
I used lots of prebuilt hal to make them work.
I have put this lineage os on miui bbs.
Here is it~
http://www.miui.com/forum.php?mod=viewthread&tid=7411849

**Comment by GuaiYiHu** [comment]
In cae of my device tree being used by other bad people for money(you know~ some guys in China have  bad quality~), I pushed my device tree and vendo onto oshcina(private repo), coz github doesn't provide private repo for free.
Can you visit gitoschina? I'm new here in the world of android. If you can help me improve the device tree, indebted forever.

**Comment by GuaiYiHu** [comment]
![screenshot_20170227-003729](https://cloud.githubusercontent.com/assets/17136448/23341711/5ee358b4-fc12-11e6-9700-7d1ab986845f.png)

**Comment by GeyerA** [comment]
Hi, sorry - took me a while. I actually do not care if people use code for money. We use Git but if you share the other platform with me, then I am willing to help on issues.
